#hub:
#  token: token
#  apimanagement:
#    enabled: true

#image:
#  registry: ghcr.io
#  repository: traefik/traefik-hub
#  tag: v3.4.0
#  pullPolicy: Always

ingressRoute:
  dashboard:
    enabled: true